#!/usr/bin/env node
var {ShapefileToGeoPackage} = require('./built/index');
var path = require('path');

console.log('GeoJSON to GeoPackage Converter');

var shapefile = path.resolve(process.cwd(), process.argv[2]);
var geoPackageFile = path.resolve(process.cwd(), process.argv[3]);
// Convert Shapefile to GeoPackage feature table
const converter = new ShapefileToGeoPackage();
converter.convert({ shapefile: shapefile, geoPackage: geoPackageFile }).then(() => {
  console.log('File conversion complete');
  console.log('Converted %s to %s', shapefile, geoPackageFile);
});